### ISSUE TITLE
Prise en charge des valeurs 0 (indisponible) et 8 (évènement)

### ISSUE THREAD

**Issue by lbaey** [sebcaps/atmofrance#10]
Quand des valeurs en dehors du tableau QUALITY_LEVEL sont reçues, il se produit une erreur :
```
2023-12-19 07:44:41.832 DEBUG (MainThread) [custom_components.atmofrance.sensor] Value for sensor Ozone-Rennes Métropole is now 0
2023-12-19 07:44:41.847 ERROR (MainThread) [homeassistant.components.sensor] atmofrance: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 575, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 959, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 517, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 93, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 276, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 399, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 479, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 745, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 845, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 789, in _async_generate_attributes
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/atmofrance/sensor.py", line 90, in extra_state_attributes
    "Libellé": self._level2string(self.native_value),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/atmofrance/sensor.py", line 95, in _level2string
    return QUALITY_LEVEL[value]
           ~~~~~~~~~~~~~^^^^^^^
KeyError: 0
```
Il serait intéressant d'interpréter les valeurs 0(indisponible), 6(extrêmement mauvais) et 8(évènement) définies dans la spec de l'API pour éviter le crash.

**Comment by sebcaps** [comment]
Salut,
Merci pour le retour. Il doit s'agir d'une mise a jour de l'API. Au moment du développement les valeurs étaient de 1 a 6.
En tous cas à corriger. 
PR bienvenue 😀

**Comment by sebcaps** [comment]
Pris en compte dans #12
