### ISSUE TITLE
Integration inopérante avec HA 2024.12

### ISSUE THREAD

**Issue by fcrozat** [sebcaps/atmofrance#23]
Depuis le passage en HA 2024.12 (et/ou le passage à python 3.13 dans le conteneur officiel HA),

l'intégration ne récupère plus de données pour ma commune (17340, Châtelaillon-Plage).

J'ai le message suivant dans les logs :
Error setting up entry Atmo France - Châtelaillon-Plage for atmofrance
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/atmofrance/__init__.py", line 44, in async_setup_entry
    databyepci = await api.get_data(entry.data[CONF_INSEE_EPCI])
                                    ~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'INSEE EPCI'

**Comment by sebcaps** [comment]
Bonjour, 
  Je n'arrive pas à reproduire le pb (en 2024.12.5).
Peux tu STP me préciser la version AtmoFrance utilisée ? Mettre le niveau de log de l'intégration à '[debug](https://www.home-assistant.io/integrations/logger/)' et poster le résultat.
Ce qui est sur c'est "qu'en plus" aucune donnée pour aucun code postal n'est dispo ce jour => cela ne fonctionne pas mais pas avec la même trace. (Trace en cas d'absence de donnée "No data for INSEE 241700434 and date 2024-12-30")

**Comment by fcrozat** [comment]
Je suis en HA 2024.12.5 / AtmoFrance version 1.0.5 (dernier commit sur github)

```
2024-12-30 10:22:12.523 INFO (MainThread) [custom_components.atmofrance] Initializing atmofrance integration with plaforms: [<Platform.SENSOR: 'sensor'>] with config: <ConfigEntry entry_id=a2ba72c4a5299ac29ad6eb4f8af74d3d version=1 domain=atmofrance title=Atmo France - Châtelaillon-Plage state=ConfigEntryState.SETUP_
IN_PROGRESS unique_id=None>
2024-12-30 10:22:13.385 DEBUG (MainThread) [custom_components.atmofrance.api] got response {'token': 'REDACTED'} 
2024-12-30 10:22:13.385 DEBUG (MainThread) [custom_components.atmofrance.api] Getting data from https://admindata.atmo-france.org/api/data/112/{"code_zone":{"operator":"=","value":"17094"},"date_ech":{"operator":">=","value":"2024-12-30"}}?withGeom=false
2024-12-30 10:22:13.449 DEBUG (MainThread) [custom_components.atmofrance.api] Got response {'type': 'FeatureCollection', 'name': 'national_data.national_ind_atmo', 'crs': {'type': 'name', 'properties': {'name': 'urn:ogc:def:crs:EPSG::3857'}}, 'features': []} 
2024-12-30 10:22:13.450 DEBUG (MainThread) [custom_components.atmofrance.api] Extracting data for INSEE 17094 and date 2024-12-30
2024-12-30 10:22:13.450 WARNING (MainThread) [custom_components.atmofrance.api] No data for INSEE 17094 and date 2024-12-30
2024-12-30 10:22:13.450 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Atmo France - Châtelaillon-Plage for atmofrance
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/atmofrance/__init__.py", line 44, in async_setup_entry
    databyepci = await api.get_data(entry.data[CONF_INSEE_EPCI])
                                    ~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'INSEE EPCI'

```

**Comment by sebcaps** [comment]
OK.
il semble qu'il y ai un pb - [général](https://forum.hacf.fr/t/nouvelle-integration-atmofrance-qualite-de-lair/24147/65) - avec l'API atmo france : aucune données n'est dispo que ce soit par l'API, le site web et donc l'intégration (qui se base sur l'API).
```
2024-12-30 10:22:13.449 DEBUG (MainThread) [custom_components.atmofrance.api] Got response {'type': 'FeatureCollection', 'name': 'national_data.national_ind_atmo', 'crs': {'type': 'name', 'properties': {'name': 'urn:ogc:def:crs:EPSG::3857'}}, 'features': []} 
``` 
ici l'attribut `features`est vide et c'est ici que les données sont récupérés

Cependant le message d'erreur, 'KeyError: 'INSEE EPCI'' n'est pas normal; ni dans ce cas ni dans un autre. 
Peut être essayer de désactiver / réactiver l'intégration ? 
En tous cas pour les données du jour c'est dépendant des données qui pour le moment ne sont pas dispo...

**Comment by fcrozat** [comment]
J'ai déjà tenté de désactiver / réactiver l'intégration, sans succès.

On va attendre que ça retombe en marche chez Atmo France alors ;)

**Comment by sebcaps** [comment]
@fcrozat , les données AirAtmo semblent de retour.
Est ce que tt est bon ? (éventuellement désactivation / réactivation de l'intégration)

**Comment by fcrozat** [comment]
C'est bon, c'est tombé en marche sans redémarrer l'intégration.
